version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8006:8000
    restart: always
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A report_by_subid worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A report_by_subid beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest